# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(max_length=1000)),
                ('tipo', models.CharField(choices=[('0', 'Preventivo'), ('1', 'Correctivo')], max_length=1)),
                ('estado', models.CharField(choices=[('0', 'Pendiente'), ('1', 'En Mantenimiento')], default=0, max_length=1)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Recurso', unique=True)),
            ],
        ),
    ]
