# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 21:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('disponible', models.BooleanField(default=False)),
                ('caracteristica', models.TextField(max_length=1000)),
                ('dias_vida_util', models.IntegerField(default=1000, verbose_name='Vida util (dias)')),
                ('ultimo_mantenimiento', models.DateField(default=None, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrador de recurso')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, unique=True)),
                ('descripcion_defecto', models.TextField(max_length=1000, verbose_name='Descripcion')),
            ],
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.TipoRecurso'),
        ),
    ]
