# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-03 01:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.IntegerField(choices=[(0, '07:30 AM'), (1, '08:15 AM'), (2, '09:00 AM'), (3, '09:45 AM'), (4, '10:30 AM'), (5, '11:15 PM'), (6, '12:00 PM'), (7, '12:45 PM'), (8, '13:15 PM'), (9, '14:00 PM'), (10, '14:45 PM'), (11, '15:30 PM'), (12, '16:15 PM'), (13, '17:00 PM'), (14, '17:45 PM'), (15, '18:30 PM'), (16, '19:15 PM'), (17, '20:00 PM'), (18, '20:45 PM')])),
                ('hora_fin', models.IntegerField(choices=[(0, '07:30 AM'), (1, '08:15 AM'), (2, '09:00 AM'), (3, '09:45 AM'), (4, '10:30 AM'), (5, '11:15 PM'), (6, '12:00 PM'), (7, '12:45 PM'), (8, '13:15 PM'), (9, '14:00 PM'), (10, '14:45 PM'), (11, '15:30 PM'), (12, '16:15 PM'), (13, '17:00 PM'), (14, '17:45 PM'), (15, '18:30 PM'), (16, '19:15 PM'), (17, '20:00 PM'), (18, '20:45 PM')])),
                ('tipo', models.CharField(choices=[('0', 'Por disponibilidad'), ('1', 'Por recurso específico')], max_length=1)),
                ('estado', models.CharField(choices=[('0', 'En Espera'), ('1', 'Aprobado'), ('2', 'Rechazado')], default='0', max_length=1)),
                ('posicion', models.IntegerField(default=1, verbose_name='posicion en cola de espera')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recursos.Recurso')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MiReserva',
            fields=[
            ],
            options={
                'verbose_name': 'mi reserva',
                'verbose_name_plural': 'mis reservas',
                'proxy': True,
            },
            bases=('reservas.reserva',),
        ),
    ]
